# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Sharmila Devi's Resume"
author: "Sharmila Devi"
logo: logo.png  # Optional: Add a logo file if needed

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: resume.tex

# Add a bibtex file for citations (remove this if not using citations)
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/sharmiladevi23/project  # Replace with your GitHub repo URL
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Use the correct branch for your repo (e.g., "main")

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
